#!/usr/bin/env php
<?php

set_time_limit(0);

$app = require(__DIR__.'/../bootstrap.php');

$app['console']->add(new CloudDeploy\Command\DeployCommand());
$app['console']->add(new CloudDeploy\Command\InstallCommand());
$app['console']->run();
