#!/usr/bin/env php
<?php
require_once(__DIR__ .'/../bootstrap.php');

set_time_limit(0);

$app = new app\App('prod', false);

$app['console']->add(new CloudDeploy\Command\NodeMonitorCommand());
$app['console']->add(new CloudDeploy\Command\InstallCommand());
$app['console']->run();
